name: Sync description and README.md to Docker Hub

on:
    push:
        branches:
            - main

jobs:
    sync-readme:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
                
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
        - 
            name: Docker Hub README & description sync
            uses: bemble/sync-readme@v1.0.0
            with:
                user: ${{ secrets.DOCKERHUB_USERNAME }}
                pass: ${{ secrets.DOCKERHUB_PASSWORD }}
                slug: ${{ secrets.DOCKERHUB_USERNAME }}/mopidy
                readme: ./README.md
                description: Mopidy music server with Iris Web-UI, Spotify support and many other extensions.
